frontend/src/components/Header.jsx
frontend/src/components/JobCard.jsx
frontend/src/components/JobFilter.jsx
frontend/src/components/Pagination.jsx
frontend/src/pages/JobsPage.jsx

feat: 헤더 수정 및 채용공고 페이지 추가

---

backend/app/core/database.py
backend/app/main.py
backend/app/models/job.py
backend/app/models/user.py
backend/app/routes/auth.py
backend/app/routes/job.py
backend/app/routes/user.py
backend/app/schemas/job.py
backend/app/services/job_service.py
backend/app/services/user_service.py
backend/pytest.ini
backend/scripts/init_db.py
backend/scripts/seed_db.py
backend/tests/conftest.py
backend/tests/test_auth.py
backend/tests/test_job.py
backend/tests/test_main.py
backend/tests/test_user.py
docs/backend/setup.md
docs/backend/structure.md

1. 모델(Model)과 스키마(Schema) 분리
models/: SQLAlchemy ORM 정의 (UserORM, JobORM)
schemas/: 요청 및 응답용 Pydantic 스키마 (JobCreate, JobOut, JobListResponse 등)
2. DB 초기화 및 샘플 데이터 스크립트 추가
scripts/init_db.py: 테이블 생성 스크립트
scripts/seed_db.py: 테스트용 샘플 데이터 삽입
3. 테스트 환경 개선
tests/conftest.py: SQLite 테스트 DB 자동 생성 및 제거
실행 시 test.db 생성 → 테스트 후 자동 삭제 처리
4. 문서 업데이트
setup.md: 초기화 및 seed 절차 문서화
Related to #43

feat: 모델-스키마 분리 및 샘플 데이터 초기화 스크립트 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/pages/ResumeAnalysisPage.css
frontend/src/pages/ResumeAnalysisPage.jsx

주요 변경 사항
- PDF 분석 페이지 기본 UI 구현
- 직무분석 페이지로 이동 가능한 탭 추가
- 탭바 및 버튼 스타일링 적용 (analysis.css)
- MUI 및 Emotion 설치로 컴포넌트 기반 스타일링 준비
설치된 의존성
- @mui/material
- @emotion/react
- @emotion/styled
- @mui/icons-material
기타
- 아직 PDF 분석 로직은 구현되지 않았으며, 이후 GPT 연동 예정

PDF 분석 페이지 UI 및 직무분석 탭 이동 기능 추가

---

backend/app/main.py
backend/app/models/keyword.py
backend/app/routes/keyword_extract.py
backend/app/schemas/keyword.py
backend/app/services/keyword_service.py

이슈 #12 
- `/api/v1/keywords/extract` 라우터 추가
- PDF 업로드 후 키워드 추출 및 DB 저장 서비스 로직 구현
- Keyword 모델 및 스키마 정의 (JSON 배열 저장 방식)

feat: 키워드 추출 API 구현

---

frontend/src/global.css
frontend/src/pages/MainPage.jsx

스크롤 불가 이슈 해결 및 JSX 문법에 맞게 className으로 수정

fix: 스크롤 불가 이슈 해결 및 JSX 문법에 맞게 className으로 수정

---

ai/.gitignore
ai/crawler/.env.example
ai/crawler/crawler_main.py
ai/crawler/repository/database.py
ai/crawler/repository/mark_closed.py
ai/crawler/repository/save_jobs.py
ai/crawler/requirements.txt
ai/crawler/services/job_classifier.py
ai/crawler/services/jumpit_crawler.py

> #31
> - 점핏 사이트에서 채용공고 스크롤 크롤링 기능 구현 (`jumpit_crawler.py`)  
> - title, company, location, experience, tech_stack, 마감일 정보 수집  
> - 직무 분류 자동화 (`classify_job`)  
> - `save_job.py`에서 DB 저장 로직 구현  
>   - URL 기준 INSERT / UPDATE  
>   - 누락된 URL은 `is_active = False` 처리  
>   - `is_active=False`인 공고는 `due_date_text = '모집마감'`으로 업데이트  
> - 총 1385개 공고 수집 및 저장 테스트 완료  
> - 기술스택 JSONB 처리 정상 적용됨

feat: 점핏 크롤링 및 DB 저장 기능 구현

---

backend/sql/20250625_db.sql
docker-compose.yml

#58 
- 로컬 PostgreSQL 데이터를 `pg_dump` 명령어로 백업하여 SQL 파일로 생성  
→ `backend/sql/20250625_db.sql`  
- `docker-compose.yml` 수정: 위 SQL 파일을 Docker 컨테이너 초기화 시 자동 실행되도록 volume 설정  
→ 컨테이너 빌드시 데이터가 자동 삽입됨

feat: .sql 및 docker-compose 최신화

---

backend/app/routes/auth_utils/kakao_auth.py
backend/app/routes/auth_utils/naver_auth.py

카카오 ,네이버 로그인 과정에서 인증 요청, 토큰 교환, 사용자 정보 요청 로직을 정리

refactor: 카카오, 네이버 인증 흐름 정리 및 코드 구조 개선

---

backend/app/routes/auth_utils/naver_auth.py
backend/app/services/user_service.py

네이버 로그인 시 social_provider가 'kakao'로 잘못 저장되던 버그를 수정하고, 정확히 'naver'로 저장되도록 처리함.

fix: 네이버 로그인 시 social_provider가 kakao로 저장되던 버그 수정

---

frontend/src/components/SocialLoginButton.jsx

fix: 네이버 로그인 인가코드 처리 로직 수정

---

frontend/src/components/SocialLoginButton.css
frontend/src/components/SocialLoginButton.jsx

feat: 로그인 UI변경

---

frontend/src/pages/TrendPage.css
frontend/src/pages/TrendPage.jsx

- 트렌드 관련 컴포넌트의 코드 정렬 및 포맷 일관화
- 기능 동작에는 변화 없음

style: 트렌드 페이지 코드 정렬

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.jsx
frontend/src/pages/RoadmapVisual.css
frontend/src/pages/RoadmapVisual.jsx

로드맵 페이지와 라우터 추가, 타임라인 컴포넌트 패키지 설치 및 반영

feat: 로드맵 페이지 추가 및 라우터 추가

---

frontend/src/pages/RoadmapVisual.css
frontend/src/pages/RoadmapVisual.jsx

feat: 로드맵 UI수정

---

frontend/src/pages/MyPage.jsx

feat: 로드맵 저장기능 추가

---

frontend/src/pages/PDFRoadmapPage.jsx

- 여러 개의 로드맵을 저장할 수 있도록 변경
- 로드맵 저장 시 날짜 정보 저장 기능 추가

feat: 로드맵 다중 저장 기능, 날짜 저장 추가

---

frontend/src/pages/MyPage.jsx

이슈 #68 
- 마이페이지 내 즐겨찾기/로드맵 구역 구조 정리
- `MyPage.jsx`
UI 구조만 변경되었으며 기능 로직은 그대로 유지됩니다.

refactor: 마이페이지 레이아웃 구조 개선

---

frontend/src/pages/Jobanalysispage.css
frontend/src/pages/Jobanalysispage.jsx

직무분석에서 해당 직무 선택후에 언어를 선택하면 해당 언어의 프레임워크만 선택 가능하도록

style: 직무 분석 페이지 레이아웃 조정

---

frontend/src/pages/ResumeAnalysisPage.css
frontend/src/pages/ResumeAnalysisPage.jsx

페이지 시각적 일관성을 위해 버튼 색상과 레이아웃 조정

style: pdf분석 페이지 UI 변경

---

frontend/src/mock/pdfroadmapmock.js
frontend/src/pages/PDFRoadmapPage.css
frontend/src/pages/PDFRoadmapPage.jsx

mock 파일과 CSS 파일을 분리하여 구조 개선 및 유지보수성 향상

refactor: PDF 로드맵 페이지 mock 데이터와 CSS 분리

---

frontend/src/App.jsx

chore: 사용하지 않는 라우터 제거

---

frontend/src/pages/Jobanalysispage.jsx

style: UI 레이아웃 위치 조정

---

frontend/src/components/Header.jsx

비로그인 시 이력서 분석 클릭 시 로그인 모달이 열리도록 변경

feat: 이력서 분석 메뉴 로그인 조건 추가

---

frontend/src/components/Header.jsx

- 비로그인 사용자가 이력서 분석 버튼 클릭 시 로그인 모달이 뜨도록 수정
- 로그인 완료 후 자동으로 /resume 페이지로 이동하도록 처리
- 상단 로그인 버튼 클릭 시에는 redirect 없이 현재 페이지 유지

feat: 이력서 분석 클릭 시 로그인 유도 및 로그인 후 자동 redirect 추가

---

frontend/src/App.jsx
frontend/src/pages/MainPage.jsx

- 비로그인 상태에서 버튼 클릭 시 로그인 모달 표시
- 로그인 성공 후 이력서 분석 페이지로 자동 이동 처리
- redirectPath 기반 이동 흐름 구현
- MainPage에서 로그인 상태 활용을 위해 props 전달 추가

feat: 취업 가능한지 알려드림 버튼 클릭 시 로그인 유도 및 로그인 후 이력서 분석 페이지 자동 이동 기능 추가

---

frontend/src/pages/Jobanalysispage.css
frontend/src/pages/Jobanalysispage.jsx

박스 테두리 굵기, 색상, 여백 등을 조정하여 UI 개선

style: 박스 UI조정

---

frontend/src/components/JobFilter.jsx
frontend/src/pages/JobsPage.css

- 하위 필터 공간 넓이 조정
- 안되던 기술스택 선택 오류 수정

feat: 공고 필터 옵션 오류 수정

---

frontend/src/components/SocialLoginButton.css

style: 구글 로그인 버튼 테두리 수정
